DROP SCHEMA IF EXISTS choose_hotels;

CREATE SCHEMA IF NOT EXISTS choose_hotels
CHARACTER SET utf8;

USE choose_hotels;


CREATE TABLE Visitor (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(255) NOT NULL,
  LASTNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);

INSERT INTO Visitor (FIRSTNAME, LASTNAME, EMAIL, PASSWORD) VALUES ('Nastya', 'Kisel', 'kisel@tut.by', 'kis');
INSERT INTO Visitor (FIRSTNAME, LASTNAME,EMAIL,PASSWORD) VALUES ('Vika', 'Kisel', 'vika@tut.by', 'vik');
INSERT INTO Visitor (FIRSTNAME, LASTNAME,EMAIL,PASSWORD) VALUES ('Lena', 'Ivanova', 'lena@tut.by', 'iva');



CREATE TABLE City (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CITYNAME VARCHAR(255) NOT NULL
);

INSERT INTO City (ID, CITYNAME) VALUES (1, 'Los-Angeles');
INSERT INTO City (ID, CITYNAME) VALUES (2, 'New-York');
INSERT INTO City (ID, CITYNAME) VALUES (3, 'Minsk');
INSERT INTO City (ID, CITYNAME) VALUES (4, 'Paris');
INSERT INTO City (ID, CITYNAME) VALUES (5, 'London');
INSERT INTO City (ID, CITYNAME) VALUES (6, 'Berlin');
INSERT INTO City (ID, CITYNAME) VALUES (7, 'Kopengagen');

CREATE TABLE Hotel (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  HOTELNAME VARCHAR(255) NOT NULL,
  HOTELADDRESS VARCHAR(255) NOT NULL,
  FK_CITY_ID INTEGER NOT NULL,
	CONSTRAINT FK_CITY FOREIGN KEY (FK_CITY_ID) REFERENCES City (ID)
	ON DELETE cascade
    ON UPDATE cascade
  
);

INSERT INTO Hotel (ID, HOTELNAME, HOTELADDRESS, FK_CITY_ID) VALUES (1, 'California', 'Los-Angeles', 1);
INSERT INTO Hotel (ID, HOTELNAME, HOTELADDRESS, FK_CITY_ID) VALUES (2, 'Hilton', 'New-York', 2);
INSERT INTO Hotel (ID, HOTELNAME, HOTELADDRESS, FK_CITY_ID) VALUES (3, 'MinskHotel', 'Minsk', 3);

CREATE TABLE Visitor_Hotel (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FK_VISITOR_ID INTEGER NOT NULL,
  FK_HOTEL_ID INTEGER NOT NULL,
  	CONSTRAINT FK_VISITOR FOREIGN KEY (FK_VISITOR_ID) REFERENCES VISITOR (ID)
	ON DELETE RESTRICT
    ON UPDATE RESTRICT,

	CONSTRAINT FK_HOTEL FOREIGN KEY (FK_HOTEL_ID) REFERENCES HOTEL (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

CREATE TABLE Room (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NUMBER_OF_PERSONS INTEGER NOT NULL,
  PRICE double NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  FK_HOTEL_ID INTEGER NOT NULL,
	CONSTRAINT FK_ROOM_TO_HOTEL FOREIGN KEY (FK_HOTEL_ID) REFERENCES Hotel (ID)
	ON DELETE cascade
    ON UPDATE cascade
  
);

INSERT INTO Room (NUMBER_OF_PERSONS, PRICE, DESCRIPTION, FK_HOTEL_ID) VALUES (2, 20, 'The room for two persons', 1);
INSERT INTO Room (NUMBER_OF_PERSONS, PRICE, DESCRIPTION, FK_HOTEL_ID) VALUES (2, 23, 'The room for two persons', 2);
INSERT INTO Room (NUMBER_OF_PERSONS, PRICE, DESCRIPTION, FK_HOTEL_ID) VALUES (3, 35, 'The room for three persons', 2);



CREATE TABLE Orders (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CONTACTNAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  
  CCNUMBER INTEGER NOT NULL,
  DATE_OF_ARRIVAL Date NOT NULL,
  DATE_OF_DISPATURE Date NOT NULL,
  FK_ORDER_ROOM_ID INTEGER NOT NULL,
	CONSTRAINT FK_ORDER_ROOM_ID FOREIGN KEY (FK_ORDER_ROOM_ID) REFERENCES room (ID)
	ON DELETE cascade
    ON UPDATE cascade
  
);

CREATE TABLE Dates (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ROOM_DATE Date NOT NULL
  
);

INSERT INTO Dates (ROOM_DATE) VALUES ('2016-04-01');
INSERT INTO Dates (ROOM_DATE) VALUES ('2016-04-02');
INSERT INTO Dates (ROOM_DATE) VALUES ('2016-04-03');

USE choose_hotels;

CREATE TABLE Room_Dates (
  ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
  FK_ROOM_ID INTEGER NOT NULL,
  FK_DATES_ID INTEGER NOT NULL,
  	CONSTRAINT FK_ROOM FOREIGN KEY (FK_ROOM_ID) REFERENCES ROOM (ID)
	ON DELETE RESTRICT
    ON UPDATE RESTRICT,

	CONSTRAINT FK_DATES FOREIGN KEY (FK_DATES_ID) REFERENCES DATES (ID)
	ON DELETE cascade
    ON UPDATE cascade
);

UPDATE Dates SET ROOM_DATE = '2016-04-07' WHERE id=7;